"""Add status to radar_images

Revision ID: 14fbc8a5637c
Revises: 9b0a20321042
Create Date: 2025-09-23 15:11:41.019113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14fbc8a5637c'
down_revision: Union[str, Sequence[str], None] = '9b0a20321042'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('radar_image', sa.Column('status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('radar_image', 'status')
    # ### end Alembic commands ###
