"""Update message

Revision ID: 1b0310b72f0b
Revises: df34b4a8214b
Create Date: 2025-10-10 00:59:36.378711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b0310b72f0b'
down_revision: Union[str, Sequence[str], None] = 'df34b4a8214b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# def upgrade() -> None:
#     """Upgrade schema."""
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.alter_column('weather_observation', 'station_id',
#                existing_type=sa.INTEGER(),
#                type_=sa.String(),
#                existing_nullable=False)
#     op.alter_column('weather_station', 'station_id',
#                existing_type=sa.INTEGER(),
#                type_=sa.String(),
#                existing_nullable=False)
#     # ### end Alembic commands ###
def upgrade():
    # Step 1: Drop the foreign key constraint
    op.drop_constraint(
        'weather_observation_station_id_fkey', 
        'weather_observation', 
        type_='foreignkey'
    )
    
    # Step 2: Change weather_station.station_id to String (parent table first)
    op.alter_column(
        'weather_station', 
        'station_id',
        existing_type=sa.INTEGER(),
        type_=sa.String(),
        existing_nullable=False
    )
    
    # Step 3: Change weather_observation.station_id to String
    op.alter_column(
        'weather_observation', 
        'station_id',
        existing_type=sa.INTEGER(),
        type_=sa.String(),
        existing_nullable=False
    )
    
    # Step 4: Recreate the foreign key constraint
    op.create_foreign_key(
        'weather_observation_station_id_fkey',
        'weather_observation',      # source table
        'weather_station',           # referenced table
        ['station_id'],              # source column
        ['station_id'],              # referenced column
        ondelete='CASCADE'
    )

# def downgrade() -> None:
#     """Downgrade schema."""
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.alter_column('weather_station', 'station_id',
#                existing_type=sa.String(),
#                type_=sa.INTEGER(),
#                existing_nullable=False)
#     op.alter_column('weather_observation', 'station_id',
#                existing_type=sa.String(),
#                type_=sa.INTEGER(),
#                existing_nullable=False)
#     # ### end Alembic commands ###

def downgrade():
    # Reverse the process
    # Step 1: Drop the foreign key
    op.drop_constraint(
        'weather_observation_station_id_fkey', 
        'weather_observation', 
        type_='foreignkey'
    )
    
    # Step 2: Change weather_observation.station_id back to Integer
    op.alter_column(
        'weather_observation', 
        'station_id',
        existing_type=sa.String(),
        type_=sa.INTEGER(),
        existing_nullable=False
    )
    
    # Step 3: Change weather_station.station_id back to Integer
    op.alter_column(
        'weather_station', 
        'station_id',
        existing_type=sa.String(),
        type_=sa.INTEGER(),
        existing_nullable=False
    )
    
    # Step 4: Recreate the foreign key with Integer types
    op.create_foreign_key(
        'weather_observation_station_id_fkey',
        'weather_observation',
        'weather_station',
        ['station_id'],
        ['station_id'],
        ondelete='CASCADE'
    )