"""Make timestamp unique on radar_images

Revision ID: 846760109d1a
Revises: 14fbc8a5637c
Create Date: 2025-09-23 15:13:15.291353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '846760109d1a'
down_revision: Union[str, Sequence[str], None] = '14fbc8a5637c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'radar_image', ['timestamp'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'radar_image', type_='unique')
    # ### end Alembic commands ###
