"""Initial migration

Revision ID: 9b0a20321042
Revises: 
Create Date: 2025-09-23 14:53:38.624587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b0a20321042'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('radar_image',
    sa.Column('image_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.TIMESTAMP(), nullable=False),
    sa.Column('range_km', sa.Integer(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('s3_key', sa.Text(), nullable=True),
    sa.CheckConstraint('range_km IN (70, 240)', name='valid_range_km'),
    sa.PrimaryKeyConstraint('image_id'),
    sa.UniqueConstraint('s3_key')
    )
    op.create_index(op.f('ix_radar_image_image_id'), 'radar_image', ['image_id'], unique=False)
    op.create_table('storm',
    sa.Column('storm_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.TIMESTAMP(), nullable=False),
    sa.Column('end_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('intensity', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('storm_id')
    )
    op.create_index(op.f('ix_storm_storm_id'), 'storm', ['storm_id'], unique=False)
    op.create_table('weather_station',
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('station_id')
    )
    op.create_index(op.f('ix_weather_station_station_id'), 'weather_station', ['station_id'], unique=False)
    op.create_table('storm_observation',
    sa.Column('obs_id', sa.Integer(), nullable=False),
    sa.Column('storm_id', sa.Integer(), nullable=False),
    sa.Column('image_id', sa.Integer(), nullable=False),
    sa.Column('centroid_lat', sa.Float(), nullable=True),
    sa.Column('centroid_lon', sa.Float(), nullable=True),
    sa.Column('area_km2', sa.Float(), nullable=True),
    sa.Column('max_intensity', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['radar_image.image_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['storm_id'], ['storm.storm_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('obs_id')
    )
    op.create_index(op.f('ix_storm_observation_obs_id'), 'storm_observation', ['obs_id'], unique=False)
    op.create_table('weather_observation',
    sa.Column('obs_id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.TIMESTAMP(), nullable=False),
    sa.Column('wind_speed', sa.Float(), nullable=True),
    sa.Column('wind_direction', sa.Float(), nullable=True),
    sa.Column('rainfall_mm', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['station_id'], ['weather_station.station_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('obs_id')
    )
    op.create_index(op.f('ix_weather_observation_obs_id'), 'weather_observation', ['obs_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weather_observation_obs_id'), table_name='weather_observation')
    op.drop_table('weather_observation')
    op.drop_index(op.f('ix_storm_observation_obs_id'), table_name='storm_observation')
    op.drop_table('storm_observation')
    op.drop_index(op.f('ix_weather_station_station_id'), table_name='weather_station')
    op.drop_table('weather_station')
    op.drop_index(op.f('ix_storm_storm_id'), table_name='storm')
    op.drop_table('storm')
    op.drop_index(op.f('ix_radar_image_image_id'), table_name='radar_image')
    op.drop_table('radar_image')
    # ### end Alembic commands ###
