"""Update message

Revision ID: df34b4a8214b
Revises: 846760109d1a
Create Date: 2025-10-10 00:32:19.348319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df34b4a8214b'
down_revision: Union[str, Sequence[str], None] = '846760109d1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weather_observation', sa.Column('temperature_c', sa.Float(), nullable=True))
    op.add_column('weather_observation', sa.Column('humidity_pct', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('weather_observation', 'humidity_pct')
    op.drop_column('weather_observation', 'temperature_c')
    # ### end Alembic commands ###
