"""finalise databse structure

Revision ID: eb737742f555
Revises: 284a310e0ff8
Create Date: 2025-10-26 02:14:49.907849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb737742f555'
down_revision: Union[str, Sequence[str], None] = '284a310e0ff8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('storm_grid',
    sa.Column('timestamp', sa.TIMESTAMP(), nullable=False),
    sa.Column('grid_data', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('timestamp')
    )
    op.drop_constraint(op.f('radar_image_timestamp_key'), 'radar_image', type_='unique')
    op.create_foreign_key(None, 'radar_image', 'storm_observation', ['timestamp'], ['timestamp'])
    op.add_column('storm', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.add_column('storm', sa.Column('duration', sa.Float(), nullable=True))
    op.add_column('storm', sa.Column('avg_centroid_x', sa.Float(), nullable=True))
    op.add_column('storm', sa.Column('avg_centroid_y', sa.Float(), nullable=True))
    op.add_column('storm', sa.Column('avg_dbz', sa.Float(), nullable=True))
    op.add_column('storm', sa.Column('avg_area', sa.Float(), nullable=True))
    op.add_column('storm', sa.Column('n_frames', sa.Integer(), nullable=True))
    op.add_column('storm', sa.Column('num_children', sa.Integer(), nullable=True))
    op.add_column('storm', sa.Column('classification', sa.String(), nullable=True))
    op.add_column('storm', sa.Column('grid_id_list', sa.Text(), nullable=True))
    op.add_column('storm', sa.Column('anchor_x_list', sa.Text(), nullable=True))
    op.add_column('storm', sa.Column('anchor_y_list', sa.Text(), nullable=True))
    op.add_column('storm', sa.Column('area_list', sa.Text(), nullable=True))
    op.drop_column('storm', 'notes')
    op.drop_column('storm', 'intensity')
    op.add_column('storm_observation', sa.Column('timestamp', sa.TIMESTAMP(), nullable=False))
    op.add_column('storm_observation', sa.Column('grid_id', sa.TIMESTAMP(), nullable=True))
    op.add_column('storm_observation', sa.Column('centroid_x', sa.Float(), nullable=True))
    op.add_column('storm_observation', sa.Column('centroid_y', sa.Float(), nullable=True))
    op.add_column('storm_observation', sa.Column('anchor_x', sa.Float(), nullable=True))
    op.add_column('storm_observation', sa.Column('anchor_y', sa.Float(), nullable=True))
    op.add_column('storm_observation', sa.Column('peak_dBZ', sa.Float(), nullable=True))
    op.add_column('storm_observation', sa.Column('area_px', sa.Float(), nullable=True))
    op.drop_constraint(op.f('storm_observation_storm_id_fkey'), 'storm_observation', type_='foreignkey')
    op.drop_constraint(op.f('storm_observation_image_id_fkey'), 'storm_observation', type_='foreignkey')
    op.create_foreign_key(None, 'storm_observation', 'storm_grid', ['grid_id'], ['timestamp'])
    op.drop_column('storm_observation', 'max_intensity')
    op.drop_column('storm_observation', 'centroid_lat')
    op.drop_column('storm_observation', 'area_km2')
    op.drop_column('storm_observation', 'centroid_lon')
    op.drop_column('storm_observation', 'image_id')
    op.drop_column('storm_observation', 'storm_id')
    op.add_column('weather_observation', sa.Column('wind_speed_knots', sa.Float(), nullable=True))
    op.add_column('weather_observation', sa.Column('wind_direction_degrees', sa.Float(), nullable=True))
    op.drop_constraint(op.f('uq_station_timestamp'), 'weather_observation', type_='unique')
    op.drop_column('weather_observation', 'wind_speed')
    op.drop_column('weather_observation', 'wind_direction')
    op.add_column('weather_station', sa.Column('lat', sa.Float(), nullable=False))
    op.add_column('weather_station', sa.Column('lon', sa.Float(), nullable=False))
    op.drop_column('weather_station', 'latitude')
    op.drop_column('weather_station', 'longitude')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weather_station', sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('weather_station', sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('weather_station', 'lon')
    op.drop_column('weather_station', 'lat')
    op.add_column('weather_observation', sa.Column('wind_direction', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('weather_observation', sa.Column('wind_speed', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.create_unique_constraint(op.f('uq_station_timestamp'), 'weather_observation', ['station_id', 'timestamp'], postgresql_nulls_not_distinct=False)
    op.drop_column('weather_observation', 'wind_direction_degrees')
    op.drop_column('weather_observation', 'wind_speed_knots')
    op.add_column('storm_observation', sa.Column('storm_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('storm_observation', sa.Column('image_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('storm_observation', sa.Column('centroid_lon', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('storm_observation', sa.Column('area_km2', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('storm_observation', sa.Column('centroid_lat', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('storm_observation', sa.Column('max_intensity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'storm_observation', type_='foreignkey')
    op.create_foreign_key(op.f('storm_observation_image_id_fkey'), 'storm_observation', 'radar_image', ['image_id'], ['image_id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('storm_observation_storm_id_fkey'), 'storm_observation', 'storm', ['storm_id'], ['storm_id'], ondelete='CASCADE')
    op.drop_column('storm_observation', 'area_px')
    op.drop_column('storm_observation', 'peak_dBZ')
    op.drop_column('storm_observation', 'anchor_y')
    op.drop_column('storm_observation', 'anchor_x')
    op.drop_column('storm_observation', 'centroid_y')
    op.drop_column('storm_observation', 'centroid_x')
    op.drop_column('storm_observation', 'grid_id')
    op.drop_column('storm_observation', 'timestamp')
    op.add_column('storm', sa.Column('intensity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('storm', sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('storm', 'area_list')
    op.drop_column('storm', 'anchor_y_list')
    op.drop_column('storm', 'anchor_x_list')
    op.drop_column('storm', 'grid_id_list')
    op.drop_column('storm', 'classification')
    op.drop_column('storm', 'num_children')
    op.drop_column('storm', 'n_frames')
    op.drop_column('storm', 'avg_area')
    op.drop_column('storm', 'avg_dbz')
    op.drop_column('storm', 'avg_centroid_y')
    op.drop_column('storm', 'avg_centroid_x')
    op.drop_column('storm', 'duration')
    op.drop_column('storm', 'parent_id')
    op.drop_constraint(None, 'radar_image', type_='foreignkey')
    op.create_unique_constraint(op.f('radar_image_timestamp_key'), 'radar_image', ['timestamp'], postgresql_nulls_not_distinct=False)
    op.drop_table('storm_grid')
    # ### end Alembic commands ###
