FROM python:3.11-slim

WORKDIR /app

COPY backend_requirements.txt .
COPY api.py .

RUN pip install --no-cache-dir -r backend_requirement.txt

EXPOSE 5000

CMD ["flask", "-A", "api", "run", "-h", "0.0.0.0", "-p", "5000"]

