services:  
  backend:  # Name of the first service. Frontend can request at "http://backend:5000/xxx"
    build: ./backend  # Build the image using the Dockerfile in this folder
    ports:
      - "5001:5000"  # Map port 5001 on the host to port 5000 in the container for host access , frontend app to communicate by 5000 
  frontend:
    build: ./frontend